@startuml sequence diagram


hide footbox

actor usuario

== Tela Inicial ==
usuario -> login: Autenticação

alt Credenciais corretas
usuario -> dashboard: Sucesso
else Credenciais incorretas
login -> login: Falha
end

== Personagens ==

alt Credenciais corretas
usuario -> menu: Acessa o menu
alt Escolhe um personagem
menu -> personagens: Acessa Personagens
personagens -> detalhes: Acessa Detalhes
else Escolhe ver todos os personagens de uma vez
personagens -> personagens: Acessa Personagens
end
else Credenciais incorretas
login -> login: Falha
end


== Perfil ==

alt Credenciais corretas
    usuario -> menu: Acessa o menu
    menu -> perfil: Acessa Perfil
else Credenciais incorretas
    login -> login: Falha
end

@enduml