@startuml use case diagram

left to right direction

package "uc Rick and Morty API"{

actor Usuario

usecase "Tela de login" as login
usecase "Dashboard" as dash
usecase "Personagens" as personagem
usecase "Detalhes Personagens" as detalhes
usecase "Filtrar personagens" as filtro
usecase "Perfil" as perfil

Usuario --> login
login --> dash
login --> personagem
login --> perfil
personagem <.. detalhes: extends
personagem <.. filtro: include

}

@enduml